app:
  build: ./docker/app
  expose:
    # fluentd
    - 24224

    # VerboseService
    - 4000
    - 4001
  links:
   - "elasticsearch"

elasticsearch:
  build: ./docker/elasticsearch
  expose:
    - 9200
    - 9300

# kibana:
#   image: kibana
#   links:
#    - "elasticsearch"
#   ports:
#    - "5601:5601"
