app1:
  build: ./docker/app1
  ports:
    # fluentd
    - 24224:24224

    # VerboseService
    - 4000:4000
    - 4001:4001
  volumes:
    - /tmp/scala-logging-efk-example/logs/app1:/var/log
  links:
    - elasticsearch

app2:
  build: ./docker/app2
  ports:
    # fluentd
    - 24224:24224

    # CalculatorService
    - 5000:5000
    - 5001:5001
  volumes:
    - /tmp/scala-logging-efk-example/logs/app2:/var/log
  links:
    - elasticsearch

elasticsearch:
  build: ./docker/elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  build: ./docker/kibana
  links:
   - elasticsearch
  ports:
   - 5601:5601
