app:
  build: ./docker/app
  ports:
    # fluentd
    - "24224:24224"

    # VerboseService
    - "4000:4000"
    - "4001:4001"
  links:
   - "elasticsearch"

elasticsearch:
  build: ./docker/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

# kibana:
#   image: kibana
#   links:
#    - "elasticsearch"
#   ports:
#    - "5601:5601"
