app:
  build: ./docker/app
  ports:
    - "4000:4000"
    - "4001:4001"


# fluentd:
#   build: ./fluentd
#   links:
#    - "elasticsearch"
#   ports:
#    - "22422:22422"

# elasticsearch:
#   build: ./elasticsearch
#   expose:
#     - 9200

# kibana:
#   image: kibana
#   links:
#    - "elasticsearch"
#   ports:
#    - "5601:5601"
